### ISSUE TITLE
[Feature Request] How to make action sheet not dismiss-able 

### ISSUE THREAD

**Issue by imjaad94** [ammarahm-ed/react-native-actions-sheet#12]
Hi, thanks a lot for such lightweight package. I was wondering if we can stop the action sheet from being dismissed. Lets say if i press on backdrop accidentally there should be a prop to disable that.
Thanks

**Comment by ammarahm-ed** [comment]
Hi there, 

I never thought about that, well that is possible. However don't you think that pressing outside the ActionSheet should close it? just like any other dialog you open, if you press outside the dialog it will close. 

This can be useful if the View behind the ActionSheet is intractable when it is opened like in taxi-apps such as Uber etc where there is a map always shown, and you can interact with both the ActionSheet and the view. 

But since you have mentioned, I will add this in the next release in a couple of days.

**Comment by imjaad94** [comment]
Thanks a lot and you are absolutely right about the usage, but you know there are some scenarios when you can't afford to dismiss the actionsheet.

**Comment by ammarahm-ed** [comment]
This has been fixed now. Next release will include this feature. I am closing this issue.

**Comment by kalimah-apps** [comment]
Which property enabled this behavior? I could not find any reference in documentation.

**Comment by ammarahm-ed** [comment]
> Which property enabled this behavior? I could not find any reference in documentation. 

Use this closable prop

**Comment by AyoCodess** [comment]
great feature!
