### ISSUE TITLE
[Question] Increase height via gesture 

### ISSUE THREAD

**Issue by johnny-mcfadden-dailypay** [ammarahm-ed/react-native-actions-sheet#148]
Is there a way to allow the user the drag the sheet up (increase in height)? It resizes perfectly and allows me to slide in down with a gesture, but would love to be able to also increase the height via gesture (if possible?)

**Comment by ammarahm-ed** [comment]
Use `initialOffsetFromBottom`

**Comment by johnny-mcfadden-dailypay** [comment]
Thanks @ammarahm-ed will give this a go! Love the API and smoothness of everything so far, super impressed!

**Comment by smit-1999** [comment]
@johnny-mcfadden-dailypay @ammarahm-ed  How do we create an ActionSheet of fixed height? 
So I want my ActionSheet to be of a fixed height eg:400. I specified that in the containerStyle property. In my ActionSheet if I have 3 options which are taking a height of 200, then the sheet takes a height of 200 rather than 400. I want the 3 options to also be shown with a height of 400.I tried using initialOffSetFromBottom but it does not work. 

Any help would be appreciated. Thanks!
