### ISSUE TITLE
[Best Practices] Share an ActionSheet across the entire app

### ISSUE THREAD

**Issue by ste7en** [ammarahm-ed/react-native-actions-sheet#149]
With the SheetManager from v0.6.0 now it is possible to easily show an ActionSheet from anywhere in the app. My question is, what is the best approach to implement an ActionSheet used in multiple parts of my app? I'm using React Navigation and the application is composed of multiple and nested navigators with screens.

Would it be a good practice to place all the shared ActionSheets in the root component, e.g. App.tsx or some of the first top-level components?

For example:
```
<Application>
  <SafeAreaProvider>
    { children }
    { actionSheets.map ... }
  </SafeAreaProvider>
</Application>
```

**Comment by ammarahm-ed** [comment]
You have thought about it right already. Since you want to be able to open sheets from anywhere in the app. The best way would be to render them at Root level of your app. You can make a `SheetsGroup` component which can hold all the sheets and be added at app level. 

```js
<App>
   <Navigator/>
   <SheetsGroup/>
</App>
``` 
One thing to remember when rendering ActionSheet at root level is that on iOS you cannot open an ActionSheet if another ActionSheet is already open. Let's say that you have two ActionSheets.

```jsx
<Properties/> // List some properties
<UserInfo/> // Info about the user
```
Suppose that the user opens the app and then opens the `Properties` Sheet. On `Properties` Sheet, the user can tap on a profile picture of the user to open `UserInfo` Sheet. Since all sheets are stacked, `UserInfo` Sheet will not appear unless `Properties` sheet is closed first on iOS so normally you will close `Properties` sheet then open `UserInfo`. 

```js
await SheetManager.close("properties_sheet");
SheetManager.open("userinfo_sheet");
```

But it's also possible to open `UserInfo` sheet while `Properties` sheet is open in background. What you need to do is render your `UserInfo` sheet inside `Properties` sheet and give it an id different than you have given in it's declaration in `SheetsGroup`. That way you can render ActionSheets within other ActionSheets without an issue.

With the second approach, now your app has, 1 Properties Sheet. And two UserInfo sheets rendered. The second `UserInfo` sheet is rendered inside `Properties` sheet.

I hope you understood this.

**Comment by ste7en** [comment]
Everything clear, thanks man!

**Comment by fukemy** [comment]
any details code example, can i return sheet from component then add to SHeetGroup? Thanks

**Comment by mehdinourollah** [comment]
I didn't quite get that would you elaborate more ?

In my case I go exactly like the Examples but the difference is that I have both "global" and local action sheets and I want to render one global (Dialog) while the other local one is opened. It shows me the functions inside the global is running but I don't see that new opened sheet on the screen.
