### ISSUE TITLE
Question regarding SheetProvider

### ISSUE THREAD

**Issue by focux** [ammarahm-ed/react-native-actions-sheet#174]
Hey 👋 , sorry for opening an issue to ask these questions—didn't know where to do it. I see that there's a new way of managing sheets using the provider and I have a few questions to see if I should migrate my project to that.

- Is it more performant to use the SheetProvider and register the sheet than just calling the SheetManager like before? I ask this because now you don't have to render the sheet, so maybe there are some gains there.

- What's the use case for not rendering the sheet using a modal? (I saw that there's a prop for this now)

- How would you handle opening sheets inside a modal? Nesting providers? Do you have to register the sheet again for that to work?

Again, sorry for opening an issue for this, I just didn't know where to do these questions. Thank you.

**Comment by ammarahm-ed** [comment]
Hey @focux 

> Is it more performant to use the SheetProvider and register the sheet than just calling the SheetManager like before? I ask this because now you don't have to render the sheet, so maybe there are some gains there.

`SheetProvider` was added to make developer experience simple, avoid boilerplate code in the app and any confusions related how and where to put the Sheet especially when opening from FlatList items. Since each Sheet will be rendered only once the app at the top level. It's more accessible + saves memory. The performance of opening the Sheets will be similar (a bit improved by not using DeviceEventEmitter anymore to send events).

> What's the use case for not rendering the sheet using a modal? (I saw that there's a prop for this now)

Sometimes you may want to render the sheet inside the current view, for example, a TabView so you can still switch tabs when the sheet is open. And possibly adding support for interactable background in the future.

> How would you handle opening sheets inside a modal? Nesting providers? Do you have to register the sheet again for that to work?

If you would like to open sheets inside a Modal, it will require another SheetProvider inside the Modal.

```js
<Modal>
<SheetProvider context="nested-provider" />
</Modal>
```
And you will need to register the Sheet again with the new provider.

```js
registerSheet("nested-sheet-id", NestedSheet, "nested-provider);
```
it's like this because on iOS you can only show a modal from another modal if it is rendered inside it.

Also I want to mention that this is not a breaking change. So if you are already using SheetManager or opening sheets with a ref, all should work the same.

**Comment by focux** [comment]
Awesome, thank you for answering my questions and for all the work you put into this library.
