### ISSUE TITLE
Allow somehow app level components to bypass the Actionsheet

### ISSUE THREAD

**Issue by kkovax25** [ammarahm-ed/react-native-actions-sheet#178]
We have an app level state components like notifications etc. Currently the only way to show any other component on the top of the actionsheet is the ExtraOverlay component. Is there by any chance an other way to bypass that zIndex 9999 i can see in the source code and display various items on top of the actionsheet like that? Would be great thanks

**Comment by ammarahm-ed** [comment]
v0.8.0 provides a zIndex prop. You can use it with nonModal based ActionSheets to do what you want.

**Comment by johnny-mcfadden-dailypay** [comment]
@ammarahm-ed 
We are also trying to display a toast but noticed it was appearing behind the action sheet overlay.  

To fix this, we tried adding `isModal` as `false` for any action sheets that needed to display a toast before closing. However, after moving to the latest version with `isModal` as `false` I noticed some padding differences at the bottom of those action sheets with `isModal` property set to `false` compared to those with `isModal` defaulted to `true`. 

We ended up removing all references to `isModal` as `false` and went with the extra overlay component prop to see how things behaved by passing in our `<Toast />` element. However, I noticed when the action sheet is closed, our animations don't run smoothly (almost seems like the toast is just unmounting). 

Looking at the docs it seems like you can only override the `z-index` property if you set `isModal` to `false`. I can go back to using this approach but would have to manually manage the padding distance on all our action sheets with this property, instead of just managing centrally in our single re-usable action sheet (that has a margin bottom on it for all action sheets). 

Don't suppose you would have any guidance for action sheets that need to display toasts that animate out over `n` seconds? 

- Do we need to use `isModal={false}` ? If so do you have any idea why the padding varies between action sheets `false` vs `true` for this property?
- Can we just continue using the extra overlay component and somehow prevent the toast animation from cutting short?
