### ISSUE TITLE
Keyboard dismissing when actions sheet is closing

### ISSUE THREAD

**Issue by focux** [ammarahm-ed/react-native-actions-sheet#18]
First of all, thanks for your work, I really love this library.

I'm having an issue when I try to focus a TextInput while the Action Sheet is closing, as you can see in the gif below, the keyboard is opening but somehow it gets dismissed by the Action Sheet. I know is the Action Sheet because when I don't close the Action Sheet, the input gets focused and the keyboard opens as expected.

It might be something related to the focus because not only the keyboard get dismissed but also the TextInpust lose the focus.
[Gif](https://s6.gifyu.com/images/Screen-Recording-2020-04-15-at-6.10.23-PM5a87ba9daef4116c.gif)

Video: https://i.imgur.com/Y5CGXwO.mp4

**Comment by ammarahm-ed** [comment]
The issue is taking place because all Modals natively are created in a seperate fragment/activity. When you call focus, it is actually hiding the actionSheet at that time, hence the keyboard is also dismissed along with it because it thinks that it was open inside the actionsheet.

What you can do is simply open the keyboard after a short delay. Maybe use the `onClose` event on ActionSheet and handle your focus call their, or maybe add a very short timeout in onClose event when you make the focus call.

**Comment by focux** [comment]
Calling the focus inside the `onClose` handler did the trick. Thank you.
