### ISSUE TITLE
Screen not responsive

### ISSUE THREAD

**Issue by SikoraKam** [ammarahm-ed/react-native-actions-sheet#182]
Screen isn't responsive after closing action sheet on android. It takes around 3 seconds until user can make any action

**Comment by ammarahm-ed** [comment]
@SikoraKam Maybe you are doing something that is blocking the Javascript thread. Try opening a blank actionsheet, it should work normally. Then debug which function call/native module is causing the issue.

**Comment by n-kulic** [comment]
@ammarahm-ed Reason for this issue is that @SikoraKam navigated to a new screen, opened `ActionSheet` and eventually closed it, but `ActionSheet` did not close in the background, this can be confirmed by setting `onClose` callback to `ActionSheet` which does not fire when ActionSheet closes

[react-native-actions-sheet](https://github.com/ammarahm-ed/react-native-actions-sheet) - **v0.8.3**

**Comment by ammarahm-ed** [comment]
@n-kulic this issue was created before 0.8.x
