### ISSUE TITLE
Can't click anything on screen briefly after close animation

### ISSUE THREAD

**Issue by NathanC** [ammarahm-ed/react-native-actions-sheet#226]
It looks like the backdrop doesn't go away until a moderate number of milliseconds after the close animation is finished. 

On my system (Android 13), when the ActionSheet is open my status bar icons dim. The other content in my screen also dims, although not as much.

When the close animation starts, my status bar remains dim, but the items in the rest of my screen immediately lighten. My status bar doesn't return to normal until a few ticks after the close animation fully completes, at which time the icons become light again. Presumably this is because the backdrop is closed then?

My main issue is that I can't click on the screen until whatever process that causes the status bar to return to normal finishes. Since the delay between closing (and even the close animation finishing) and being able to click is noticeable, this makes it feel like the interface is laggy if the user tries to click somewhere.

Is there a way to change this behavior, so things become clickable as soon as the close animation starts?

**Comment by NathanC** [comment]
Setting `isModal={false}` prevents the status bar dimming, but it appears that the delay till intractable is still the same.

**Comment by NathanC** [comment]
I tried to hook into `onClose` and set some state that would enable `backgroundInteractionEnabled`, but `onClose` doesn't fire until the background becomes intractable again (and there doesn't seem to be an `onBeforeClose`).

**Comment by ammarahm-ed** [comment]
Hi, can you reproduce this in the example app? I don't see any delay in the ActionSheet examples.

**Comment by Amusa-Paulos** [comment]
It has happened to me before, it was because I was updating `redux` state - which will then update a content somewhere in the UI - in the `onClose` event   
   
so it might be because you were updating the state in the `onClose` event or there was a bad state handling while the sheet was still opened   
   
so try to check if you're handling your state well   
   
and it would be helpful if you can also state what you were using the sheet for
