### ISSUE TITLE
Accessibility Flags on Backdrop

### ISSUE THREAD

**Issue by benkaiser** [ammarahm-ed/react-native-actions-sheet#245]
Thanks for the fantastic library!
Would you be open to accepting a PR to add accessibility flags to the touchable backdrop? Looking to have the library consumer provide an accessibility label + accessibility role to the touchable backdrop.

After testing out this library with TalkBack on Android, I discovered that although I can focus on the backdrop nothing is announced (i.e. there is no name for the button).

This could look as simple as providing a `overlayProps` as an optional prop to ActionSheet and spreading that onto the overlay component.

**Comment by aleberguer** [comment]
Hello! we need exactly this! 
In our case, when talkback is on, it focuses only on the backdrop. As a result, any interaction with the action sheet becomes impossible. 
The changes in that PR would be very helpful.

**Comment by benkaiser** [comment]
@aleberguer can the user not still select other elements in the action sheet? The issue I'm seeing is purely that if the user does focus the backdrop, it reads nothing out, which isn't helpful. But the user can still focus on the items in the sheet.

Also, would you take a look at the PR too @aleberguer to see if it's what you need? #246

**Comment by aleberguer** [comment]
Yeah, I can't interact with the elements inside the action sheet because the backdrop gets focused no matter what.
The changes in your PR will help us properly manage the accessibility on both the backdrop and the actionsheet.
Here is what I'm currently facing:

https://user-images.githubusercontent.com/5271876/207137509-4f7559ff-c753-4314-aada-2a5ef911d2d8.mp4

@ammarahm-ed is there a chance that you could merge #246? I think it's a simple change that will help developers who are focusing on accessibility.

**Comment by tomaszukovskij** [comment]
Hi there. Does this still work? I am using the latest 0.8.21 version. Have a component build like that
`import Modal from 'react-native-actions-sheet';`
![image](https://github.com/ammarahm-ed/react-native-actions-sheet/assets/25223364/f0402d2b-0cf3-485d-98e1-7bf8c02de760)
### 

but props do not work. The reader still reads the background as GROUP. Any ideas? Thanks
