### ISSUE TITLE
Rewrite the module in TypeScript

### ISSUE THREAD

**Issue by ncuillery** [ammarahm-ed/react-native-actions-sheet#5]
Hey 👋 

Thank you for doing this, how about rewriting the module in TypeScript and generate the type definition file instead of maintaining it by hand?

I made a couple of PR to fix issues that would have been detected by using TypeScript.

**Comment by ammarahm-ed** [comment]
Hi there, thank you for sending some useful pull requests. I have merged all of them. A rewrite of the module in typescript for me has no benefit to the end users of this library since the defined `.ts` file does the job although it is a bit of a hassle maintaining another file. I added it for intellisense to work properly in Visual Studio Code. Currently there are no plans for converting the whole module to typescript.

**Comment by ncuillery** [comment]
You're right, there is no benefit for the end users. It's really for the maintainer and people who'd like to contribute (like me 😉).

You seem to use TS outside this library, do you have a strong opinion for NOT converting the whole module to TypeScript? In other words, if I send that in a PR, would you consider merging it?

**Comment by ammarahm-ed** [comment]
If you send in a PR, I will merge it.
