### ISSUE TITLE
Avoid explicit usage of `children` in the documentation

### ISSUE THREAD

**Issue by ncuillery** [ammarahm-ed/react-native-actions-sheet#6]
I find a bit weird to show an explicit usage of the `children` props:
```
<ActionSheet
  children={<View/>}
/>
```
instead of 
```
<ActionSheet
  <View/>
/>
```
I have never seen this before
Even if it syntaxically correct, it adds verbosity for... nothing?

What do you think?

**Comment by ammarahm-ed** [comment]
At a point I thought that too, why use `children` and not just wrap everything inside the `ActionSheet`. It can be done in both ways, and I have mentioned both of them in the documentation. 

```jsx
<ActionSheet>
<View/>
</ActionSheet>
```

I still think it doesnt make a difference as its possible in which ever way you like and mentioned in the docs too. what do you think?

**Comment by breynolds-dev** [comment]
For what it's worth there is a rule for the react eslint that recommends using it wrapped instead of passed as a prop.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-children-prop.md

While it may be the same thing under the hood, I agree that wrapped is a little more clear as to what's happening with the components.

**Comment by ammarahm-ed** [comment]
After a bit of research I have removed `children` usage from the docs. I am closing this issue now as it has been fixed. Thanks @ncuillery  and @breynolds-dev for making it clearer to me.
