### ISSUE TITLE
Scrollview not working on android

### ISSUE THREAD

**Issue by rafaelbpa** [ammarahm-ed/react-native-actions-sheet#9]
Hello,

When I have a scrollview as the first children of the react-native-action-sheet on android it is not working. My component simply just don't scroll. Works perfectly on iOS, but not on Android.

Is something wrong with the library or am I missing something?

**Comment by ammarahm-ed** [comment]
Hi there, 

Thanks for using this module. You are facing this issue because the ActionSheet uses a ScrollView underneath to handle all the touches due to its native performance. 

On iOS by default nested scrolling is enabled, so scrollviews inside ScrollViews work fine however on android nested ScrollView will not work as expected by default. 

There is a prop `nestedScrollEnabled` on android which you can use to enable nested scrolling on android but it is not well tested for our use case so I would suggest you to try it out and see if it is working fine.

Go to `/node_modules/react-native-actions-sheet/src/index.js` and inside the ScrollView add the following prop:
`nestedScrollEnabled={true}`

Now in your own ScrollView also enable nestedScrolling by `nestedScrollEnabled={true}` prop and give your ScrollView a **Fixed Height** so the Scroll Wont cover the whole screen but instead scroll inside the parent ScrollView as it should probably. 

Once you have implemented it, try it out and see how it works for you and what problems you face so that we could fix the for the next release and add proper support for nestedScrollViews.

I have tested it and its working this way, but try it out before I make any changes in the repo and make a new release.

**Comment by rafaelbpa** [comment]
Oh, I see. The way you told me it is working. Thanks a lot! Good work!

**Comment by ammarahm-ed** [comment]
Scrolling is implemented properly and will be available in the next release!

**Comment by lukebars** [comment]
@ammarahm-ed scrollview works like a charm in iOS, android doesn't scroll at all on `0.4.2`: 

```jsx
<ActionSheetComponent
    ref={ref}
    gestureEnabled={true}
    nestedScrollEnabled={true}
>
    <ScrollView contentContainerStyle={styles.container}>
        <Text theme={theme} size="l" style={styles.instruction}>    
            {loremipsum}
        </Text>
    </ScrollView>
</ActionSheetComponent>
```

**Comment by ammarahm-ed** [comment]
@lukebars check the example App and compare your implementation. You should set nestedScrollEnabled on the ScrollView, not the ActionSheet.
